#!/bin/sh
set -e

IMAGE_NAME=ruby
VERSION=2.4-fishtrip
REMOTE_URL=registry-internal.cn-beijing.aliyuncs.com/fishtrip

echo "1. build image $IMAGE_NAME:$VERSION"
echo

cp ../../aliyun.sources.list.online ./sources.list
cp ../../hosts ./hosts
docker build -t $IMAGE_NAME:$VERSION .
rm -rf ./sources.list
rm -rf ./hosts

echo
echo "2.push image to remote $REMOTE_URL/$IMAGE_NAME:$VERSION"
echo
docker tag $IMAGE_NAME:$VERSION $REMOTE_URL/$IMAGE_NAME:$VERSION
docker push $REMOTE_URL/$IMAGE_NAME:$VERSION
