#!/bin/sh
set -e

IMAGE_NAME=ruby
VERSION=2.2-fishtrip
REMOTE_URL=registry-internal.cn-beijing.aliyuncs.com/fishtrip
SOURCES_LIST_FILE="../../aliyun.sources.list.online"

echo "#### Start build image $IMAGE_NAME:$VERSION"
echo

cp $SOURCES_LIST_FILE ./sources.list

BUILD_COMMAND="docker build -t $IMAGE_NAME:$VERSION ."
echo "#### Build command: $BUILD_COMMAND"

eval $BUILD_COMMAND

rm -rf ./sources.list

echo
echo "#### Start push image to remote $REMOTE_URL/$IMAGE_NAME:$VERSION"
echo
docker tag $IMAGE_NAME:$VERSION $REMOTE_URL/$IMAGE_NAME:$VERSION
docker push $REMOTE_URL/$IMAGE_NAME:$VERSION
