#!/bin/sh
set -e

IMAGE_NAME=fishtrip-ruby-2.2
VERSION=latest

echo "local build $IMAGE_NAME:$VERSION"
echo

cp ../../aliyun.sources.list.local ./sources.list
cp ../../host ./host
docker build -t $IMAGE_NAME:$VERSION .
rm -rf ./sources.list
