#!/bin/sh
set -e

IMAGE_NAME=fishtrip-ruby-2.3
VERSION=latest

echo "online build $IMAGE_NAME:$VERSION"
echo

cp ../../aliyun.sources.list.online ./sources.list
cp ../../host ./host
docker build -t $IMAGE_NAME:$VERSION .
rm -rf ./sources.list
